services:
  db:
    image: postgres:17-alpine
    container_name: banklify-db-demo
    environment:
      POSTGRES_USER: banklify_user
      POSTGRES_PASSWORD: banklifypassword
      POSTGRES_DB: banklify-db
    volumes:
      - banklify_demo_data:/var/lib/postgresql/data
      - ./dump-banklify-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banklify_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/afulvio1/banklify-backend:main
    container_name: banklify-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banklify-db
      SPRING_DATASOURCE_USERNAME: banklify_user
      SPRING_DATASOURCE_PASSWORD: banklifypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank-network

  frontend:
    image: ghcr.io/afulvio1/banklify-frontend:main
    container_name: banklify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bank-network

volumes:
  banklify_demo_data:

networks:
  bank-network:
    driver: bridge
