services:
  db:
    image: postgres:15-alpine
    container_name: banklify-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_segreta
      POSTGRES_DB: banklify_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump_database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/tuo-username/nome-repo-backend:main 
    container_name: banklify-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banklify_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password_segreta
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank-network

  frontend:
    image: ghcr.io/tuo-username/nome-repo-frontend:main
    container_name: banklify-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge
